import type { Metadata } from "next";
import {
  ClerkProvider,
  
} from '@clerk/nextjs'

import "./globals.css";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <ClerkProvider>
    <html lang="en">
      <body>
        <Header></Header>
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
